### ISSUE TITLE
Show terminal while running script

### ISSUE THREAD

**Issue by renet** [yahely/PreCommitHookPlugin#1]
I'm running a few tests on the code in my pre-commit-hook.sh script, which take quite some time (up to 1 minute - yeah I know it should be optimized) to finish. Thus, it would be great to have a terminal visible that shows the output of the script so I can see the details of an eventually failing test and also to better see the progress of the script.

Would you mind adding this in a future release?

**Comment by yahely** [comment]
I'll see what I can do about it in the next few weeks.

If you want, you can pull request it.

Thanks.

**Comment by gshmu** [comment]
i think show scipt output will be better.

I using "&> /path/to/file" for this
