### ISSUE TITLE
How to use in windows

### ISSUE THREAD

**Issue by xxxzhi** [yahely/PreCommitHookPlugin#10]
How to use this Plugin in windows? I create pre-commit-hook.sh in windows, but It is invalid.

**Comment by x0ptr** [comment]
you can use a pre-commit-hook.bat file.

commit for windows support:
f235c8a46275f9c5d96ce1f203392a6fe47cdc75

**Comment by x0ptr** [comment]
#11 there is an pull request for that.

**Comment by rvanlaak** [comment]
Can this MR please be merged and released, as installing the plugin in PHPStorm now doesn't include the Windows-fix.

... is there a way to manually install `master`, because PHPStorm doesn't accept the downloaded .zip directly. Do plugins have to be compiled?

**Comment by philipbulley** [comment]
@yahely currently the latest version on https://plugins.jetbrains.com/plugin/9278-pre-commit-hook-plugin is 0.3.1. Would you mind releasing a version containing #5 please?

**Comment by leebake** [comment]
@rvanlaak you can clone repository in Intellij and prepare jar file. Then you can install it by "Install plugin from disk"

**Comment by yahely** [comment]
Just released version 0.4.1, Thanks for the pull requests!
