### ISSUE TITLE
Can you make it scrollable?

### ISSUE THREAD

**Issue by claucookie** [yahely/PreCommitHookPlugin#13]
Usually when I ran all the test on my pre-commit script I get a long console error which is not scrollable.
Can you make it possible? It is very annoying since the test which failed is at the end.

<img width="916" alt="screen shot 2017-10-30 at 16 59 47" src="https://user-images.githubusercontent.com/2184653/32184368-e9e29040-bd93-11e7-8ffd-4a4f3a357be5.png">

**Comment by yahely** [comment]
You're welcome to contribute to this project and make it scrollable. :)
