### ISSUE TITLE
Please provide a code sample for pre-commit-hook.sh

### ISSUE THREAD

**Issue by agrublev** [yahely/PreCommitHookPlugin#2]
I keep trying stuff and have no idea why its not working. Outputting the Terminal would be awesome.

But just a good sample script would help.

**Comment by yahely** [comment]
I hope this will help you. 
I'm checking 'ddescribe' string in the js files. 
If you have more questions, don't hesitate to ask :)

```#!/bin/bash

set -o pipefail

export PATH=$PATH:/devutils

ddescribe_files=$(grep -niro '\bddescribe\b' htdocs/FP/Tests/Js/ | cut -d":" -f1-2)

if [ $? -eq 0 ]
then
     echo "There is 'ddescribe' in your JS tests code, please change to 'describe':"
     echo $ddescribe_files
     exit 1
fi
