### ISSUE TITLE
hope can support sub git

### ISSUE THREAD

**Issue by bluelovers** [yahely/PreCommitHookPlugin#21]
```
main folder
- .git
- packages
- - mysubgitfolder
- - - .git
- - - pre-commit-hook.bat
```

when commit in mysubgitfolder can **auto** search `pre-commit-hook.bat` in `packages/mysubgitfolder`

if not exists then search main folder

**Comment by yahely** [comment]
If you're using git, you better use [git hooks](https://git-scm.com/book/gr/v2/Customizing-Git-Git-Hooks).
