### ISSUE TITLE
Can't Build Plugin From Scratch For IntelliJ 2016.3

### ISSUE THREAD

**Issue by duffymo** [yahely/PreCommitHookPlugin#3]
Your Subversion pre-commit plug appears to be just what I need, but I'm having two problems.

First, I run on Windows 7 in IntelliJ 2016.3.  I put a file named pre-commit-hook.sh at my project root that invokes the hook I want to execute.  But when I try to commit a file I get a popup that says the script "is not a valid Win32 application".

I could install bash and associate it with .sh files, but that adds to the requirements I'll impose on other IntelliJ users.  I'd like to avoid that if I could.

I thought I'd pull down your code and build it locally.   I'd like to be able to externalize the name of the script that's executed so I could substitute a Windows .bat or .cmd of my choice.

I Mavenized it and pulled into dependencies for the IntelliJ openapi JAR version 7.0.3 (that's the latest available in Maven) and intellij-idea JAR version 10.0 (there is also a version 12.0).  I get a compilation error because the CheckinProjectPanel in the openapi JAR does not include the method getSelectedChanges().

I've played with all the versions of the JAR available to me, without success.

The dates on the JARs are old.  I wonder if the API has changed.  If I could find docs on how to use the latest version of the API I'd try to revamp what you have.  I'm a neophyte on writing IntelliJ plugins.

I'd love to collaborate to include the Maven changes I've made in case they'd be helpful, but I need some help in either finding the proper version of that class or replacing the functionality with something else.

**Comment by yahely** [comment]
Hi, 
I can add a support for .bat files. 
Is it still relevant? 
Thanks.
