### ISSUE TITLE
Can we have a pre-commit-hook.bat executed on Windows?

### ISSUE THREAD

**Issue by Schepp** [yahely/PreCommitHookPlugin#4]
I had the suspicion and it turned out to be true, that the proposed setup will not run on Windows (native, w/o Linux bash). Would it be possible to have the plugin execute a `pre-commit-hook.bat`-file instead on Windows?

**Comment by yahely** [comment]
Yes, It has been supported now.
Enjoy.

**Comment by ahryhorieva** [comment]
Hi Yahel, I added `pre-commit-hook.bat` to my project, but the plugin still tries executing .sh file instead. Could you suggest what might be the problem?

**Comment by jackieliu-52** [comment]
@anna-hryhorieva 
You can write your own plugin and deploy a plugin into jar file,I have used *.py for my needs in that way.
