### ISSUE TITLE
Pre-commit hook freezes even when running pre-commit-hook.sh script manually has no issue.

### ISSUE THREAD

**Issue by nddipiazza** [yahely/PreCommitHookPlugin#8]
Pre-commit hook freezes and never returns. 

When I run pre-commit-hook.sh script manually, it returns fine and shows no symptoms of issue.

Might be a red herring but this seemed to start happening when i ran the `pre-commit-hook.sh` script using intelliJ from a `pre-commit-hook.sh` bash run configuration.

I've tried since deleting the run configuration but it does nothing. still frozen every time i try to use it now.

**Comment by yahely** [comment]
Can you upload a `pre-commit-hook.sh` script that reproduces the problem?

**Comment by nddipiazza** [comment]
Cant repro
Dont even remember this anymore
